blank_issues_enabled: true
contact_links:
  - name: PSKReporter.info
    url: https://pskreporter.info
    about: PSKReporter amateur radio propagation reporting system
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Get help from the Home Assistant community
